#!/usr/bin/env python

from datetime import datetime
def calc_holidays(d1, d2):
    d1 = datetime.strptime(d1, "%Y-%m-%d")
    d2 = datetime.strptime(d2, "%Y-%m-%d")
    return abs((d2 - d1).days)
#

from datetime import date

def diff_dates(date1, date2):
    return abs(date2-date1).days

def main():
    d1 = date(2013,1,1)
    d2 = date(2013,9,13)
    result1 = diff_dates(d2, d1)
    print '{} days between {} and {}'.format(result1, d1, d2)
    print ("Happy programmer's day!")

main()

New Year's Day
Wednesday, January 1, 2020 
Martin Luther King, Jr. 
Day
Monday, January 20, 2020 
President's 
Day
Monday, February 17, 2020 
Memorial 
Day
Mo
nday, May 25, 2020 
Independence 
Day
Saturday, July 4, 2020* 
Labor 
Day
Monday, September 7, 2020 
Veterans' 
Day
Wednesday, November 11, 2020 
Thanksgiving 
Day
Thursday, November 26, 2020 
Christmas 
Day
Friday, December 25, 2020  
