#!/usr/bin/env python
def calc_holidays():
int
list
return(


#
New Year's Day
Wednesday, January 1, 2020 
Martin Luther King, Jr. 
Day
Monday, January 20, 2020 
President's 
Day
Monday, February 17, 2020 
Memorial 
Day
Mo
nday, May 25, 2020 
Independence 
Day
Saturday, July 4, 2020* 
Labor 
Day
Monday, September 7, 2020 
Veterans' 
Day
Wednesday, November 11, 2020 
Thanksgiving 
Day
Thursday, November 26, 2020 
Christmas 
Day
Friday, December 25, 2020 
